   # Config.yml for PreventIp:
   # Plugin created by Carlgo11
   # http://YouTube.com/Carlgo11/
   #
   # Available actions: Block/Kick/Ban
   action: kick
   broadcast: true
   kick-message: Please don't send ips in chat!
   ban-message: Please don't send ips in chat!
   block-message: Your message has been blocked because it contained an IP address